### PR TITLE
Fix browser support configurations of Array

### LINKED ISSUE #826: Array.from and some es6 features are not provided for Android
http://kangax.github.io/compat-table/es6/

```
/* Polyfill service v3.8.1
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: android/4.4.0
 * Features requested: WeakMap,WeakSet,default
 * 
 * - _mutation, License: CC0 (required by "Element.prototype.after", "Element.prototype.append", "Element.prototype.before", "Element.prototype.prepend", "Element.prototype.remove", "Element.prototype.replaceWith", "default")
 * - Element.prototype.after, License: CC0 (required by "default")
 * - Element.prototype.append, License: CC0 (required by "default")
 * - Element.prototype.before, License: CC0 (required by "default")
 * - Element.prototype.matches, License: CC0 (required by "Element.prototype.closest", "default")
 * - Element.prototype.closest, License: CC0 (required by "default")
 * - Element.prototype.prepend, License: CC0 (required by "default")
 * - Element.prototype.remove, License: CC0 (required by "default")
 * - Element.prototype.replaceWith, License: CC0 (required by "default")
 * - Number.isNaN, License: MIT (required by "Set", "default")
 * - Object.assign, License: CC0 (required by "default")
 * - setImmediate, License: CC0 (required by "Promise", "default")
 * - Promise, License: MIT (required by "default")
 * - Set, License: CC0 (required by "default")
 * - String.prototype.endsWith, License: CC0 (required by "default")
 * - String.prototype.includes, License: CC0 (required by "default")
 * - String.prototype.startsWith, License: CC0 (required by "default")
 * - URL, License: CC0 (required by "default")
 * - document.visibilityState, License: CC0 (required by "default") */
```

### PR DESCRIPTION
**Pull request by falsandtru**
Fixes #826.

### CODE REVIEW

**Comment by falsandtru** [comment]
Fixes #826.

**Comment by triblondon** [comment]
Thanks, pushing to a local branch for CI...

You may also be interested in https://github.com/Financial-Times/polyfill-service/issues/107, which I'm working hard on at the moment.

**Comment by falsandtru** [comment]
Yes, self-update is the best way. This fix works until adding its feature.

Question. Is there a better way to run CI tests by myself?

**Comment by triblondon** [comment]
Can you cite some compat data here?  CI is fine, and I'm happy to merge if you can confirm that your proposed targeting matches documented compatibility,

**Comment by falsandtru** [comment]
Okay,

image

## from

image

## of

image

**Comment by falsandtru** [comment]
@triblondon Is this enough?

**Comment by JakeChampion** [comment]
@falsandtru, thanks for the PR. The changes look good, thanks for supplying the support data. Before I can merge this in, I need to check that you have read and agreed to our [contribution terms](https://cdn.polyfill.io/v2/docs/contributing#contribution-terms):

> All contributions to the polyfill service are made under the MIT licence. It is important therefore that you agree to the following when contributing code to the service:
> - Any contribution I make to the polyfill service by way of Pull Request contains only data that is:
>   - wholly my own work, upon which I am legally permitted to grant a licence; or
>   - wholly the work of individuals within the same organisation to which the copyright in all work created by employees is assigned, of which I am a current employee and authorised representive for the purposes of this contribution, and which is legally permitted to grant a licence; or
>   - licensed by the original author under the MIT licence or equivalent terms
> - In respect of any part of my contribution that is not already available under an MIT or compatible licence, I hereby grant to the Financial Times Limited (FT) and to recipients of software distributed by the FT a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable license to make, have made, use, offer to sell, sell, import, and otherwise transfer the data.
> 
> It is helpful to us if you can clearly state your agreement to the above terms when creating a pull request. If you don't, you may be asked to post a followup comment to accept the terms, before we can merge your PR.

**Comment by falsandtru** [comment]
@JakeChampion I agree with contribution terms of this project.

**Comment by JakeChampion** [comment]
Thanks for helping improve our browser support for these polyfills. Your changes will be released as part of version `3.11.0`. 

In case you are not aware, this project has a set of [contribution rewards](https://cdn.polyfill.io/v2/docs/contributing#contribution-rewards) awarded to community members who have a pull request merged into the project.

> ## Contribution rewards
> 
> We want to encourage more people to get involved in the polyfill service, so the Financial Times is pleased to offer one month's free premium access to all FT content (normally $50) to anyone who has a pull request merged in this repository. [Claim your free access.](https://docs.google.com/a/ft.com/forms/d/1aykPiYBwqKpKY6nvGVi43wOU_5epr3XLgE00Vi52SMQ/viewform)

**Comment by falsandtru** [comment]
Oh, I didn't know that. Thanks for your kindness!

**Pull request merged**
