### PR TITLE
Fix document.currentScript

### PR DESCRIPTION
**Pull request by falsandtru**
The current code won't find a script that has not been added yet even after added.

### CODE REVIEW

**Comment by JakeChampion** [comment]
Can you add a test for this?

**Comment by falsandtru** [comment]
Okay, I'll try it. However, it may be impossible to make this polyfill in some browsers. Then we need to accept this limitation. So please run tests before adding tests.

**Comment by falsandtru** [comment]
Added.

**Comment by JakeChampion** [comment]
@falsandtru This seems to currently fail in IE 8:

```
Failed tests:
 - ie 8 (Sauce results: https://saucelabs.com/tests/6841a3ed79f1453a81b32aa57a5c4169)
    -> document.currentScript
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=document.currentScript
```

**Comment by falsandtru** [comment]
@JakeChampion Please rerun tests to know the failed test.

**Comment by JakeChampion** [comment]
Rerun the tests:
```
Tunnel closed

Failures:
 • ie/8 (targeted) [https://saucelabs.com/tests/ec5c1dcbf2db412495c299b8a7bbe8b8]
    -> document.currentScript
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=document.currentScript
```

**Comment by falsandtru** [comment]
Thanks, fixed it.

**Comment by JakeChampion** [comment]
@falsandtru It passes CI now :-) Would you be able to [resign our CLA](https://github.com/Financial-Times/polyfill-service/pull/975#issuecomment-261414409), we added a bot to keep track of them and have decided to start afresh with the signatures.

**Comment by falsandtru** [comment]
I agreed.

**Review by JakeChampion — APPROVED** [review]

**Pull request merged**
