### PR TITLE
Element.prototype.classlist for svg elements

### PR DESCRIPTION
**Pull request by jkimbo**
Make sure classList works on svg elements

### CODE REVIEW

**Comment by triblondon** [comment]
I'm getting 3 test failures, in IE 6, 7 and 8.

**Comment by triblondon** [comment]
If you have a Sauce Labs account and you set the appropriate env vars (`SAUCE_USER_NAME`, `SAUCE_API_KEY`) you can run `grunt ci` to use Sauce to run tests across our key browser targets.  Otherwise just fire up some VMs :-)

**Comment by jkimbo** [comment]
@triblondon found the issue, IE8 and below doesn't support svg at all...

I've added a check to skip the test if there isn't svg support since it's not particularly relevant.

**Comment by triblondon** [comment]
Looks good.  See #423 for local PR.

**Pull request closed without merging**
