### PR TITLE
Added blissfuljs alias, as discussed in #594

### PR DESCRIPTION
**Pull request by LeaVerou**
As discussed in #594.
Thanks in advance! Hope I didn’t miss anything :)

Edit: Not sure why Travis is failing. It seems that the tests are passing, but some `SAUCE_USER_NAME` and `SAUCE_API_KEY` environment variables aren’t defined. No idea what these are for, didn't see anything in the contributing docs about them…

### CODE REVIEW

**Comment by jonathantneal** [comment]
Awesome! Looks good.

**Comment by LeaVerou** [comment]
Thanks!

Any ideas why if I visit https://cdn.polyfill.io/v2/polyfill.min.js?features=blissfuljs|always (the `always` flag is for testing) it doesn't show anything? Perhaps it needs time to propagate?

**Comment by JakeChampion** [comment]
This feature will be out when 3.3 is deployed. The deployment process is currently manually done.

**Comment by JakeChampion** [comment]
I've created an issue to track automatic deployments - https://github.com/Financial-Times/polyfill-service/issues/599

**Pull request merged**
