### PR TITLE
Need to set Picture polyfill IE to 7+ to support Methode

### PR DESCRIPTION
**Pull request by debugwand**
https://github.com/Financial-Times/polyfill-service/issues/794

### CODE REVIEW

**Comment by triblondon** [comment]
Picturefill ambitiously claims "No known unsupported browsers"

https://github.com/scottjehl/picturefill#support

We do not host the tests for picturefill and I don't know if they run them in IE7.  I'm pretty relaxed about serving this in IE7 though, especially since its not in the default set.

@debugwand have you tested the picturefill polyfill in IE7?

**Comment by debugwand** [comment]
Essentially yes, I tested in the environment that Methode runs in - IE10 in Compatibility mode (which equates to IE7) and this change makes the difference between things working and not working

**Comment by triblondon** [comment]
OK. I'd be more comfortable with this if you could create a simple reduced test case and test it in standalone IE10 compat mode and also in real IE7, just to make sure it doesn't throw any errors.  Typically I use jsbin.com for this.  The JSBin UI does not work in IE7, but you can view the output of the bin only by replacing the `/edit` with `/quiet` on the URL.

I'm also having trouble testing your change because you have not created a branch, and my git-fu doesn't seem to be good enough to figure out how to push your branch to our main fork in a way that keeps it associated with this pull request.  Do you know how to do that?

**Comment by debugwand** [comment]
I have given you access on my fork for you to able to get a copy. I cannot push branches to this repo.

I've run an isolated test in real IE7 on browserstack, it doesn't throw any errors.

With the fix, the image shows up in IE10 with IE7 browser mode, but not IE10 with IE7 browser mode AND IE7 document mode, nor in real IE7.

**Comment by JakeChampion** [comment]
Didn't mean to merge this Pull Request, apologies. I have reverted and will recreate it.

I've now learnt how to push `master` branches from forks into our repository without automatically merging them. Pasting here for others to read. It uses Github's `hub` tool.

``` bash
❯ hub checkout https://github.com/Financial-Times/polyfill-service/pull/797
Branch debugwand-master set up to track remote branch master from debugwand.
Switched to a new branch 'debugwand-master'
❯ git push -u origin debugwan-master:debugwan
```

**Comment by bjfletcher** [comment]
@JakeChampion @debugwand is all this work complete?

**Comment by JakeChampion** [comment]
It is in version 3.10, which is yet to be released.

**Comment by bjfletcher** [comment]
@JakeChampion Great, is there an issue for the 3.10 release? We can track it.

**Comment by JakeChampion** [comment]
@bjfletcher Yes :-) -- https://github.com/Financial-Times/polyfill-service/issues/835

**Comment by tracker1** [comment]
@triblondon check out the master locally... then (optionally) create your own branch to work in... 

`git pull git@github.com:debugwand/polyfill-service.git master`

will pull in the remote changes into your branch, with a merge if needed....  from here, you can push into the upstream master.

As soon as a merge/push with the associated git hash is committed to the local master, the PR will be marked as merged.

**Pull request merged**
