### PR TITLE
polyfill URL for all IEs and Edge browsers

### PR DESCRIPTION
**Pull request by JakeChampion**
Fixes issue #941

### CODE REVIEW

**Comment by triblondon** [comment]
Does the detect pass in Edge?  We should try to ensure the detect fails where we want the polyfill to take effect.

**Comment by falsandtru** [comment]
I tried to run `'searchParams' in nativeURL` on Edge, then this code returns `false` correctly. And it would be tested by existing tests.

https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/URL/tests.js#L113

**Comment by triblondon** [comment]
Does https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/URL/detect.js return false in Edge?  If so, the proposed change is fine.

**Comment by triblondon** [comment]
Looks like detect fails in Edge, so we're good:

image

**Review by triblondon — APPROVED** [review]

**Pull request merged**
