### PR TITLE
Support EventListenerOptions

### PR DESCRIPTION
**Pull request by falsandtru**

### CODE REVIEW

**Comment by falsandtru** [comment]
Can you run this test?

**Comment by triblondon** [comment]
Sure, will do that today.  By the way, I just noticed you're in Tokyo, Japan based on your profile.  I am also based in Tokyo.  If you'd be interested in speaking face to face feel free to drop me a mail or come along to one of our meetups (https://frontend.connpass.com)!

**Comment by falsandtru** [comment]
What a coincidence! Sadly, I cannot speak English. So I'm unable to speak with you 😢. Thanks for inviting me!

Now, I found https://github.com/WICG/EventListenerOptions. Can we use that?

**Comment by triblondon** [comment]
Well, your written English is nearly perfect.  `EventListenerOptions` is interesting.  If it is exposed as a global we could use it for feature detection, but there are already browsers that support capture and passive listeners without supporting them via a specialised interface.  So I guess you'd need both that and your more complex detect (which is very clever, by the way).

Like I said in https://github.com/Financial-Times/polyfill-service/issues/857, it's not ideal to have to serve the `Event` polyfill to browsers that don't need it, so do you have a strong preference for doing it this way instead of creating a separate `EventListenerOptions` polyfill?

**Comment by triblondon** [comment]
Hmm, something not working on CircleCI... @JakeChampion any idea what's going on?

**Comment by falsandtru** [comment]
>  your written English is nearly perfect.

Thanks, I'm happy to hear that.

Hm, in short, we cannot use the WICG's polyfill under their license? About a separateness, I hope to implement to existing files to separate difficulty and steps because I don't know your system well. Or if you add the placeholder, it is helpful to me. About the ci failure, at least, `window.addEventListener` in my impl doesn't work before completing dom loading. It must be `document.createElement("div").addEventListener`.

Just a note, the difference of EventListenerOptions feature support confuses the order of calling.

``` js
addEventListener('click', function(){console.log(0)});
addEventListener('click', function(){console.log(1)}, {});
```

In this code, browsers return `0, 1` if they support EventListenerOptions, otherwise they return `1, 0`.

**Comment by falsandtru** [comment]
I fixed that point for now.

**Comment by falsandtru** [comment]
Could you run tests with permission?

```
Running "saucelabs:ci" (saucelabs) task
Warning: SAUCE_USER_NAME and SAUCE_API_KEY must be set in the environment Use --force to continue.
Error: SAUCE_USER_NAME and SAUCE_API_KEY must be set in the environment
  at Object.<anonymous> (/home/ubuntu/polyfill-service/tasks/grunt/saucelabs.js:60:20)
  at Object.<anonymous> (/home/ubuntu/polyfill-service/node_modules/grunt/lib/grunt/task.js:255:15)
  at Object.thisTask.fn (/home/ubuntu/polyfill-service/node_modules/grunt/lib/grunt/task.js:73:16)
  at Object.<anonymous> (/home/ubuntu/polyfill-service/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/home/ubuntu/polyfill-service/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/home/ubuntu/polyfill-service/node_modules/grunt/lib/util/task.js:293:12)
  at /home/ubuntu/polyfill-service/node_modules/grunt/lib/util/task.js:220:11
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by JakeChampion** [comment]
Rerunning now

**Comment by falsandtru** [comment]
Thanks! `Event/tests.js` of this pr is passed with chrome/30 (Android 4.4), but ci is failed with all browsers. I have no idea how to pass the tests.

**Comment by triblondon** [comment]
Looks like some sauce labs timeouts.  Sorry about this @falsandtru, but we refactored the node tests and there's a conflict there.  Could you resolve, and then we'll try again?

**Comment by falsandtru** [comment]
Thanks, I resolved it!

**Comment by falsandtru** [comment]
Hm... I'll try to separate the implementations as it is said at https://github.com/Financial-Times/polyfill-service/pull/905#issuecomment-253085925 for now.

**Comment by JakeChampion** [comment]
@falsandtru This is what fails on CI:
```
Failures:
 • chrome/48 (targeted) [https://saucelabs.com/tests/51a40109f9f04b28b979b91dd31d1ace]
    -> Event
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event
 • firefox/44 (targeted) [https://saucelabs.com/tests/9f5741e0da0e44c8b24861f3a6beec3a]
    -> Event
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event
 • ie/14 (targeted) [https://saucelabs.com/tests/76b883ee2bd04de09f48dc174542988a]
    -> Event
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event
 • ie/13 (targeted) [https://saucelabs.com/tests/4588833e6708441bb218b3f1a5b6c689]
    -> Event
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event
 • ie/11 (targeted) [https://saucelabs.com/tests/ea4ca18048744a608b1c7e345ebef943]
    -> IntersectionObserver (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=IntersectionObserver (timeout after 30000ms, 2 retries)
    -> CustomEvent (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=CustomEvent (timeout after 30000ms, 2 retries)
    -> Promise (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Promise (timeout after 30000ms, 2 retries)
    -> fetch (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=fetch (timeout after 30000ms, 2 retries)
    -> navigator.sendBeacon (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=navigator.sendBeacon (timeout after 30000ms, 2 retries)
    -> Event (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event (timeout after 30000ms, 2 retries)
 • ie/10 (targeted) [https://saucelabs.com/tests/93df4461a27d4f06811648da5bd42cda]
    -> IntersectionObserver (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=IntersectionObserver (timeout after 30000ms, 2 retries)
    -> CustomEvent (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=CustomEvent (timeout after 30000ms, 2 retries)
    -> Promise (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Promise (timeout after 30000ms, 2 retries)
    -> fetch (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=fetch (timeout after 30000ms, 2 retries)
    -> navigator.sendBeacon (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=navigator.sendBeacon (timeout after 30000ms, 2 retries)
    -> Event (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event (timeout after 30000ms, 2 retries)
 • ie/9 (targeted) [https://saucelabs.com/tests/c3ef94f7a76040b599b9e5dc5294cd65]
    -> IntersectionObserver (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=IntersectionObserver (timeout after 30000ms, 2 retries)
    -> CustomEvent (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=CustomEvent (timeout after 30000ms, 2 retries)
    -> Promise (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Promise (timeout after 30000ms, 2 retries)
    -> fetch (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=fetch (timeout after 30000ms, 2 retries)
    -> navigator.sendBeacon (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=navigator.sendBeacon (timeout after 30000ms, 2 retries)
    -> Event (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event (timeout after 30000ms, 2 retries)
    -> matchMedia (timeout after 30000ms, 2 retries)
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=matchMedia (timeout after 30000ms, 2 retries)
 • ie/8 (targeted) [https://saucelabs.com/tests/a9ca0f60779441cc9332ee2c31da4458]
    -> XMLHttpRequest
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=XMLHttpRequest
    -> Event
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event
 • ie/7 (targeted) [https://saucelabs.com/tests/adcb718cd561438e8d07b75f6112ed3d]
    -> XMLHttpRequest
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=XMLHttpRequest
    -> Event
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event
 • safari/9 (targeted) [https://saucelabs.com/tests/cefc1159438941b0b61c5f4abb4ef6c7]
    -> Event
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event
 • safari/8 (targeted) [https://saucelabs.com/tests/7c53fac69a364feba5c28dcf57c35aee]
    -> Event
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event
 • android/5.1 (targeted) [https://saucelabs.com/tests/a0581ba7bc434681bcbb795b56aaf057]
    -> Event
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event
 • android/4.4 (targeted) [https://saucelabs.com/tests/a87ac45126674af89d81b15c36f3fb03]
    -> Event
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Event

```

**Comment by triblondon** [comment]
@falsandtru will you be finishing this work?

**Comment by triblondon** [comment]
Closing this one as we haven't heard from @falsandtru, who is probably too busy to complete the work. Feel free to reopen if you want to finish this.

**Pull request closed without merging**
