### PR TITLE
[fix] add `append(...args)` to fragments too

### PR DESCRIPTION
**Pull request by WebReflection**
Specifications make append available for document fragments too.

It's easy to fail a feature detection via 'append' in document
assuming append can be then used via document.createDocumentFragment().append(...) too.

This change fixes the issue and avoid conflicts with other libraries.

### CODE REVIEW

**Comment by caub** [comment]
isn't it redundant with https://github.com/Financial-Times/polyfill-service/pull/1269 ?

**Comment by WebReflection** [comment]
This is DocumentFragment append, which doesn't inherit from Element.

**Comment by JakeChampion** [comment]
I made the tests output some more information:
```
Failures:
 - ie/7:
    -> DocumentFragment.prototype.append passes a feature detect
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=DocumentFragment.prototype.append
       'DocumentFragment.prototype' is null or not an object
 - ie/7:
    -> DocumentFragment.prototype.append has correct instance
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=DocumentFragment.prototype.append
       undefined instanceof 
function Function() {
    [native code]
}

 - ie/7:
    -> DocumentFragment.prototype.append has correct name
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=DocumentFragment.prototype.append
       Function expected
 - ie/7:
    -> DocumentFragment.prototype.append has correct argument length
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=DocumentFragment.prototype.append
       'fragment.append.length' is null or not an object
 - ie/7:
    -> DocumentFragment.prototype.append can append elements
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=DocumentFragment.prototype.append
       Object doesn't support this property or method

```

**Review by JakeChampion — APPROVED** [review]

**Comment by JakeChampion** [comment]
@WebReflection Here are some stats on a months worth of origin traffic for IE 7/8/9. In that month we had ~5 million hits to origin and ~2.5% of those were IE 7/8/9.

screen shot 2017-09-01 at 18 04 00

**Comment by WebReflection** [comment]
2.5 but only 1/5 of that looks like IE7 ... I don't think the world should put any effort to support less than IE9 in 2017, nothing would work there anyway, unless you write code like it's 1999 and if you do, I'm sorry to hear that, no polyfill can save you.

Thanks for sharing the graph though, interesting and terrifying at the same time.

**Pull request merged**
