### PR TITLE
Allow polyfills to be organised into subfolders in the source tree

### PR DESCRIPTION
**Pull request by triblondon**
This PR allows polyfills to be organised into subfolders, but also permits the current structure.  This is intended to make it easier to maintain the project after adding large polyfills such as Intl, as discussed in #108.

### CODE REVIEW

**Comment by caridy** [comment]
@triblondon do we need any update on this PR before I try to get the intl polyfill integrated?

**Comment by triblondon** [comment]
Looks like it needs a merge from master. I'll put it on my list, and try to do it this week.

**Comment by triblondon** [comment]
@caridy Branch updated.  You should also have invite to be a collaborator on the repo.  Do you see it?

**Comment by caridy** [comment]
awesome, I will give it a try today.

**Comment by triblondon** [comment]
Thanks.  Build tests are failing due to a very simple issue I merged without testing properly.  I'll sort that out and merge an update, but you're good to go in the meantime.

**Comment by triblondon** [comment]
Hooray, build is now passing on this branch.

**Comment by JakeChampion** [comment]
@triblondon Should this be closed?

**Comment by triblondon** [comment]
Yes, looks like it's fully merged into master

**Comment by caridy** [comment]
thanks a lot @triblondon.

qq, what will be the process to update Intl from now on considering that we only need to update package.json and run the update library task?

**Comment by triblondon** [comment]
Do exactly that.  And then go through the normal RC -> release process, https://github.com/Financial-Times/polyfill-service/issues/328#issue-59561080

**Pull request closed without merging**
