### PR TITLE
use URI Template in API doc

### PR DESCRIPTION
**Pull request by tpluscode**
I find the API documentation unclear and took me a while to understand.

What do you think about using a standard URL template (RFC6570)? I didn't include the `<var></var>` tags. Please edit as you see fit. I just wasn't sure what to outline.

Given such change you could get rid of the `WHERE` column completely. Up to you

### CODE REVIEW

**Comment by triblondon** [comment]
Never heard of this RFC, but it sounds like a good idea if it's a common standard.  Do you know of other popular API docs that use this format?

**Comment by tpluscode** [comment]
GitHub API is probably the most prominent example. See the example response in their docs: https://developer.github.com/v3/repos/#response

Also, anyone using [HAL](http://stateless.co/hal_specification.html) is using that format. Although it's not explicitly referenced in the HTML doc, they did mention it in their [RFC draft](https://tools.ietf.org/html/draft-kelly-json-hal-08#section-5.1)

**Comment by tpluscode** [comment]
Ah, there's the documentation bit I was looking for: https://developer.github.com/v3/#hypermedia

**Comment by triblondon** [comment]
Hmm, but their method documentation actually uses basically the same convention that we already use:

image

**Comment by tpluscode** [comment]
True, which kind of surprises me. Such syntax is only good for concrete segments so maybe it's good enough for them. 

In your case URI Template allows

1. being explicit about optional dot-prefixed extension (`{.min}`)
1. explicitly listing query string params (`{?a,b,c}`)

I find this cleaner than having to look at both the template and the table to determine where each option belongs to.

**Comment by triblondon** [comment]
Jake, you're keen on this?  I am mildly against because it means writing the params in two places and they are likely to get out of date.  I don't hear anyone else saying the docs are unclear and I don't see any popular examples of services documenting their APIs like this...  I do appreciate the suggestion but I'm not totally sold tbh.

**Comment by JakeChampion** [comment]
I'm very happy to hear comments about our documentation, thanks for taking the time to give us feedback. I agree with the concern @triblondon has made about it potentially becoming out of date documentation as the parameters would exist in two places.

**Comment by triblondon** [comment]
OK, let's stick with the format we have.  @tpluscode I'm sorry to decline your suggestion and thanks for making it, we do appreciate the input and hope you feel we gave it a fair hearing!

**Pull request closed without merging**
