### PR TITLE
Update/Swap dependencies for versions which do not have vulnerabilities in them according to WhiteSource

### PR DESCRIPTION
**Pull request by JakeChampion**
High severity fixes:
 - Updated express to fix a ReDos vulnerability (High severity) -- https://github.com/Financial-Times/polyfill-service/commit/7385812483d6cd84370a50893d8496b9242184a8

- Swapped marked for marky-markdown as marked is not maintained and contains an XSS vulnerability (High severity) -- https://github.com/Financial-Times/polyfill-service/commit/1c0868f4bb0d05e3b74fa397787931234e7f92b2

Medium severity fixes:
- Removed shrink-ray (brotli) hasn't been maintained, moved the module into our codebase as it is MIT licensed, this lets us update shrink-ray's dependencies and fix more vulnerabilities (Medium severity) -- https://github.com/Financial-Times/polyfill-service/commit/9374d910fafec078c25a3d186dfc80cdf926cb71

- Updated fastly module to avoid memory exposure and ReDos vulnerabilities -- https://github.com/Financial-Times/polyfill-service/commit/639b1123a36f68466fa7083e42506889e8aa85e0

Low severity fixes:
- Updated babel to fix a ReDos vulnerability (Low severity) -- https://github.com/Financial-Times/polyfill-service/commit/70bb753230ac87d07c33548256df9d8d12a05ecd

- Updated eslint and fixed all the linting issues that were being found with the newer version - https://github.com/Financial-Times/polyfill-service/commit/70e7ca0ebc55a25d103143efdcc4e5ebb10d7f4b

- Stopped any timers running whilst we run the test suite, the timers were causing the process to not exit therefore not finishing the build on CI -- https://github.com/Financial-Times/polyfill-service/commit/cc3e404d09de00332d8d60a05ae2cc5d6e2954dd

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
Can I suggest something like https://nodesecurity.io/ which will check this for you on each PR (or they have a CLI tool which you can run with tests or deploys)

**Comment by JakeChampion** [comment]
@AdriVanHoudt We are using WhiteSource to do the same thing that nodesecurity offers, this was the first time we have had it run.

**Comment by AdriVanHoudt** [comment]
Oh yeah that looks way more extensive :D From the picture on https://www.whitesourcesoftware.com/open-source-security/ it looks like they use nodesecurity to track vulnerabilities so 👌

**Comment by JakeChampion** [comment]
@AdriVanHoudt I will definitely be adding it to our CI process though, that is the plan :-)

**Pull request merged**
