### PR TITLE
Corrected indexOf casing in matchMedia polyfill

### PR DESCRIPTION
**Pull request by donatasbacius**

### CODE REVIEW

**Comment by doodlemoonch** [comment]
+1

**Comment by triblondon** [comment]
Ooh, thanks.  Can you add a test maybe for both the add and remove listeners?

**Comment by triblondon** [comment]
@donatasbacius doodlemoonch if one of you could sort out a couple of tests here that would be appreciated.

**Comment by triblondon** [comment]
Seems pointless to keep this hanging around.

**Pull request merged**
