### PR TITLE
Adds test to Object.create for API objects as it fails in IE8

### PR DESCRIPTION
**Pull request by AlbertoElias**
So API objects in IE8 aren't instances of `Object`, so Object.create doesn't work on them. I've created the test that fails for this use case. I'm not really sure what the ideal solution to this problem is though

### CODE REVIEW

**Comment by triblondon** [comment]
I'm not sure what you mean by "API object".  Do you mean "DOM object"?!

If so, I think I fixed it, and edited your test to clarify that language.

**Comment by AlbertoElias** [comment]
I meant Native Objects

**Comment by AlbertoElias** [comment]
@triblondon how's that?

**Comment by triblondon** [comment]
I'm not convinced that the polyfill for CustomElements is needed to solve this problem :-)

**Comment by AlbertoElias** [comment]
Oops! Let me remove those files!

**Comment by AlbertoElias** [comment]
Done

**Pull request merged**
