### PR TITLE
Picturefill (local for #437)

### PR DESCRIPTION
**Pull request by triblondon**
See #437

### CODE REVIEW

**Comment by triblondon** [comment]
OK, currently fails the detect in all browsers :-)

@jonathan-fielding try running the service with `grunt dev` and then load http://localhost:3000/test/tests?feature=Picture&mode=targeted in Safari

**Comment by jonathan-fielding** [comment]
Tests added, also got the detect working BUT am hoping @scottjehl gets back to me about why the picturefill polyfill doesnt expose HTMLPictureElement

**Comment by triblondon** [comment]
@jonathan-fielding one other thing I've just realised - this needs to be called `HTMLPictureElement` not `Picture`.

**Comment by scottjehl** [comment]
@triblondon picturefill polyfills all responsive image markup, not just `picture`. So `img[srcset]` and `img[sizes]` are in there too, independent of picture. Just in case that's helpful to know.

**Comment by jonathan-fielding** [comment]
Updated the name, and the test

**Comment by jonathan-fielding** [comment]
The new test didnt work so reverted

**Comment by jonathan-fielding** [comment]
Ok thats working now and I have updated the unit tests run in polyfill service as they broke with new version of Picturefill

**Comment by triblondon** [comment]
Asked Jonathan to remove the tests because they are testing the polyfill's proprietary API, not the spec.

**Pull request merged**
