### PR TITLE
add yandex on iOS check

### PR DESCRIPTION
**Pull request by salzhrani**
There is a mobile variant and this checks for it and aliases it

### CODE REVIEW

**Comment by JakeChampion** [comment]
Thank you for the pull-request, I believe we already detect this user-agent as ios_saf.
```
➜  curl https://polyfill.io/v3/normalizeUa -H "user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) AppleNews/608.0.1 Version/2.0.1"
ios_saf/10.0.0
```

If you have other user-agents which show this is not the case, please re-open this pull-request and we can look into improving the service with your change :-)

**Comment by salzhrani** [comment]
from the PR
```
curl https://polyfill.io/v3/normalizeUa -H "user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 YaBrowser/18.10.3.114.10 Mobile/15E148 Safari/605.1"

other/0.0.0
```

**Comment by JakeChampion** [comment]
@salzhrani Doe the mobile variant use the same browser under the hood?

**Comment by salzhrani** [comment]
@JakeChampion depends on the OS, all browsers on iOS must use the system webview i.e. `saf_ios`.

**Comment by JakeChampion** [comment]
Thanks @salzhrani, the code for this part of the project now has it's own repository, I have opened an issue there for this and will close this pull-request.

Issue: https://github.com/Financial-Times/polyfill-useragent-normaliser/issues/6

**Pull request closed without merging**
