### PR TITLE
Correct robots.txt syntax

### PR DESCRIPTION
**Pull request by chenrui333**
Just found out that your robots.txt syntax is not correct. And I have referenced it with my VCL code too. 

Thus, filing this PR to fix it.

### CODE REVIEW

**Comment by chee** [comment]
thank you !

**Comment by chee** [comment]
@Financial-Times/origami-core it looks like outside contributions can't be deployed to heroku staging?

**Comment by JakeChampion** [comment]
Yes, outside contributions do not get access to secrets in our GitHub CI, they didn't get them in CircleCI either. We need to review the code and check it doesn't do anything bad like steal our secrets or leak them, once that is done we then need to push the commits to our origin and then CI will run with our secrets

**Comment by chenrui333** [comment]
This is actually a very simple robots.txt syntax fix. :D

**Review by JakeChampion — COMMENTED** [review]
We want robots to crawl our website which is why the disallow is empty. I think the change suggested here would make robots not crawl any page of our website.

**Comment by chenrui333** [comment]
> We want robots to crawl our website which is why the disallow is empty. I think the change suggested here would make robots not crawl any page of our website.

Yeah, you are right, I thought you want to disallow the web crawlers for the polyfill service though.

If you want to allow every UA, then you should use:

```
User-agent: *
Allow: /
```

The syntax there is just incorrect.

**Comment by chenrui333** [comment]
@JakeChampion, sorry, you are right. (just did a test with https://en.ryte.com/free-tools/robots-txt/?refresh=1&url=Polyfill.io&useragent=Googlebot&submit=Evaluate)

```
User-agent: *
Disallow:
```

is equivalent to 

```
User-agent: *
Allow: /
```

I still feel the former syntax is little bit weird though.

**Comment by chee** [comment]
aren't they also both equivalent to not having a `robots.txt` at all?

**Comment by chee** [comment]
anyway, it looks like this is working as expected. thank you for looking out for us, @chenrui333

**Comment by chenrui333** [comment]
> aren't they also both equivalent to not having a `robots.txt` at all?

yeah, I think so.

**Comment by chenrui333** [comment]
> anyway, it looks like this is working as expected. thank you for looking out for us, @chenrui333

np at all, happy to help.

**Pull request closed without merging**
