### PR TITLE
Changed version resolution from lte to lt

### PR DESCRIPTION
**Pull request by seanmtracey**
Seems that <= didn't work, but < does work.

### CODE REVIEW

**Comment by triblondon** [comment]
I think this bug is papering over a different problem.  The specifier as it exists already should match 44:

image

I agree it doesn't, though:

http://cdn.polyfill.io/v2/polyfill.js?features=Array.prototype.find&ua=chrome/44

```
/* For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: chrome/44.0.0
 * Features requested: Array.prototype.find
 *  */
```

So this needs a bit more investigation, probably [starting here](https://github.com/Financial-Times/polyfill-service/blob/master/lib/index.js#L67).

**Comment by JakeChampion** [comment]
Would it be because Chrome has version numbers such as 44.0.2526.106, which is bigger than 44?

**Comment by triblondon** [comment]
Looks like there was a bug in the version of the semver parser that we were using.  I updated it and it looks good now.

**Comment by JakeChampion** [comment]
Should we add this as a test case?

**Pull request closed without merging**
