### PR TITLE
Ie11 mobile matches

### PR DESCRIPTION
**Pull request by CheloXL**
Hope this time I get this correctly...
wp_ss_20170126_0001
wp_ss_20170126_0002

### CODE REVIEW

**Comment by CheloXL** [comment]
Ok.. didn't get it correctly on the first try... now it should be ok.

**Review by JakeChampion — APPROVED** [review]

**Comment by JakeChampion** [comment]
@CheloXL This will also serve the polyfill to Edge mobile, is that the intention? If not, the range should be `10 - 11`.

**Comment by CheloXL** [comment]
@JakeChampion Mmm... I don't have Edge mobile to test. I guess since Edge supports matches, it should not be needed. But again, I don't have a way to test. Will change as you suggested and let others test on Edge mobile

**Review by JakeChampion — APPROVED** [review]

**Comment by triblondon** [comment]
Fixes #1065

**Pull request merged**
