### PR TITLE
Update min mobile safari version for Math.trunc

### PR DESCRIPTION
**Pull request by mbrevda**
From what I can tell,  safari on iOS doesn't have `Math.trunc` in versions < 8.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc#Browser_compatibility

### CODE REVIEW

**Comment by JakeChampion** [comment]
Looks good, thanks @mbrevda, before I can merge this you'll also need to [accept our contribution terms](https://polyfill.io/v2/docs/contributing#contribution-terms). Written agreement here in the PR would be fine.

**Comment by mbrevda** [comment]
I agree

**Review by JakeChampion — APPROVED** [review]

**Comment by lenovouser** [comment]
@JakeChampion [cla-assistant.io](https://cla-assistant.io/) might be something for you 😃

**Comment by JakeChampion** [comment]
@lenovouser That looks super useful! Thank you very much for sharing it! :-D

**Comment by mbrevda** [comment]
Thanks!

**Comment by JakeChampion** [comment]
Thanks for the PR! 

Did you know we offer one month's free premium access to all FT content (normally $50) to anyone who has a pull request merged in this repository? If you want to claim it, there's [one Google form](https://docs.google.com/a/ft.com/forms/d/1aykPiYBwqKpKY6nvGVi43wOU_5epr3XLgE00Vi52SMQ/viewform) to fill out :-)

**Comment by mbrevda** [comment]
Other than a publication of sorts, I don't even know what you guys do. What
I do know is that you provide an amazing public service. So hey, I'm just
glad I could help out!

On Thu, Nov 17, 2016, 7:22 PM Jake Champion notifications@github.com
wrote:

Thanks for the PR!

Did you know we offer one month's free premium access to all FT content
(normally $50) to anyone who has a pull request merged in this repository?
If you want to claim it, there's one Google form
https://docs.google.com/a/ft.com/forms/d/1aykPiYBwqKpKY6nvGVi43wOU_5epr3XLgE00Vi52SMQ/viewform
to fill out :-)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/Financial-Times/polyfill-service/pull/988#issuecomment-261310430,
or mute the thread

**Pull request merged**
