### PR TITLE
Add Samsung target to String pad polyfills.

### PR DESCRIPTION
**Pull request by ruiaraujo**

### CODE REVIEW

**Comment by JakeChampion** [comment]
@AdaRoseEdwards, would you be able to review this PR at all? If not, that's okay :-) 

@ruiaraujo Could you provide screenshots of the tests for these polyfills passing in the samsung browser versions targeted by your PR please?

**Comment by AdaRoseCannon** [comment]
Looks accurate for Samsung Internet as it is a Chrome 57 feature :)

**Comment by AdaRoseCannon** [comment]
If you want to run the tests in the Samsung Browser it is also installable on GDE devices such as Pixel and Nexus Phones.

**Comment by ruiaraujo** [comment]
@AdaRoseEdwards Thanks for the hint.

@JakeChampion Here you go.
screenshot_20170604-190634

**Review by JakeChampion — APPROVED** [review]

**Pull request merged**
