### PR TITLE
Chrome 31 doesn't have native Promise yet

### PR DESCRIPTION
**Pull request by jhiswin**
Just need to change to Chrome 32 as the endpoint #501

### CODE REVIEW

**Comment by triblondon** [comment]
I think we're right here already actually.  The config says we serve the polyfill to `* - 31`, and MDN says Promises became native in 32.  The numbers are inclusive - 31 in our config means everything < 32, following standard semver conventions.

**Comment by jhiswin** [comment]
@triblondon the problem is that when testing with Chrome 31, the polyfill service does not serve promises.
BTW you guys shuold apply for a free browserstack account.  It's free for open source project devs.

**Comment by jhiswin** [comment]
This is what I get from the polyfill service using Chrome 31 on Windows 7 (on BrowserStack):

/\* Rerun without minification for verbose metadata */

(function(undefined) {Element.prototype.matches=Element.prototype.matches||Element.prototype.webkitMatchesSelector;Element.prototype.closest=function(t){for(var e=this;e;){if(e.matches(t))return e;e=e.parentElement}return null};Object.assign=function(r,t){for(var n,e,a=1;a<arguments.length;++a){e=arguments[a];for(n in e)Object.prototype.hasOwnProperty.call(e,n)&&(r[n]=e[n])}return r};String.prototype.includes=function(t,e){if("object"==typeof t&&t instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(t,e)};}).call('object' === typeof window && window || 'object' === typeof self && self || 'object' === typeof global && global || {});

**Comment by triblondon** [comment]
See #501.  Re browserstack, I have been thinking of moving over from Sauce to Browserstack but I don\t know anything about their platform.  If you'd like to submit a PR to add a `browserstack.js` task to `tasks/` that would be super appreciated.  The current CI task is sauce.js

**Pull request closed without merging**
