### PR TITLE
Fix the validation order

### PR DESCRIPTION
**Pull request by falsandtru**

### CODE REVIEW

**Comment by JakeChampion** [comment]
@falsandtru What prompted this change? Is it a spec violation?

**Comment by falsandtru** [comment]
`!(descriptor instanceof Object)` check never works because of `'value' in descriptor`. So that validation is moved to work before using `descriptor`.

**Comment by JakeChampion** [comment]
@falsandtru Could you add a test to cover this change to ensure we don't regress on this?

**Comment by falsandtru** [comment]
Fixed.

**Comment by JakeChampion** [comment]
@falsandtru I refactored your test to use proclaim. It is currently running the suite on CI :-)

**Pull request merged**
