### PR TITLE
update Intl.js polyfill to version 1.1.0

### PR DESCRIPTION
**Pull request by caridy**
https://github.com/andyearnshaw/Intl.js/releases/tag/v1.1.0

### CODE REVIEW

**Comment by caridy** [comment]
The failure is due to some problems with soucelab it seems.

**Comment by triblondon** [comment]
The CI failure is because it's running on your fork, which doesn't have our Sauce credentials available. 

Your update seems to change a lot of whitespace.  Any way you can avoid that?

**Comment by triblondon** [comment]
Thanks for the update, by the way, much appreciated!

**Comment by caridy** [comment]
@triblondon not much I can do about that, this is data from CLDR project that is being digested and reconfigured for Intl. The only real change here is in package.json, then running the update-polyfills grunt task to generate all the new stuff.

**Comment by triblondon** [comment]
https://github.com/Financial-Times/polyfill-service/pull/624

**Comment by caridy** [comment]
thanks @triblondon, please, let me know when this hits prod.

additionally, do you guys have some stats about the usage of this polyfill?

**Comment by JakeChampion** [comment]
3.3 is now in QA which is located at qa.polyfill.io. You can track the release to live/production at issue #625

**Comment by JakeChampion** [comment]
3.3 is now live :-)

**Comment by caridy** [comment]
:clap:

**Pull request merged**
