### PR TITLE
Serve Element.prototype.closest to Android versions < 5

### PR DESCRIPTION
**Pull request by falsandtru**
image

### CODE REVIEW

**Comment by falsandtru** [comment]
Now I'm not sure about android browser on AndroidOS5. Seems like it uses the latest browser. Maybe this pr can be fixed such as

``` diff
-       "android": "<5.1",
+       "android": "<5",
```

But I don't have AndroidOS5. Can you check the android browser version on AndroidOS5?

**Comment by JakeChampion** [comment]
They all come back as Chrome 49:
<details><summary>

Samsung Galaxy S6</summary>


screen shot 2016-09-12 at 22 49 13
</details>

<details><summary>

Google Nexus 6</summary>


screen shot 2016-09-12 at 22 49 45
</details>

<details><summary>

Moto X 2nd Gen</summary>


screen shot 2016-09-12 at 22 50 09
</details>

<details><summary>

Moto G 2nd Gen</summary>


screen shot 2016-09-12 at 22 50 34
</details>

**Comment by falsandtru** [comment]
Then we can change to `<5` because Element.closest is supported in Chrome 49.

**Comment by JakeChampion** [comment]
I agree 👍

**Comment by falsandtru** [comment]
Yeah, I fixed it.

**Pull request merged**
