### PR TITLE
Polyfilling screen.orientation

### PR DESCRIPTION
**Pull request by wheresrhys**
@triblondon

### CODE REVIEW

**Comment by wheresrhys** [comment]
fixes https://github.com/Financial-Times/polyfill-service/issues/402

**Comment by wheresrhys** [comment]
Should this be in the default set of polyfills?

**Comment by triblondon** [comment]
Looks fine.  Could put it in the default set though it's not an ideal implementation - it doesn't update as the screen orientation changes, and I prefer to only make polyfills default if they are complete.

**Comment by wheresrhys** [comment]
Good point about orientation changes. I'll mull over the best
implementation. Maybe a getter? Or could watch events. Which'd you prefer?

On Monday, June 15, 2015, Andrew Betts notifications@github.com wrote:

> Merged #403 https://github.com/Financial-Times/polyfill-service/pull/403
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Financial-Times/polyfill-service/pull/403#event-330573422
> .

## 

---

This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Pull request merged**
