### PR TITLE
fix: Function.prototype.bind was failing on new BoundFn() (local for #483)

### PR DESCRIPTION
**Pull request by triblondon**
See #483

### CODE REVIEW

**Comment by vvo** [comment]
Awesome

**Comment by vvo** [comment]
Android failed in one check, can you relaunch? I bet saucelabs had issues here

**Comment by triblondon** [comment]
Restarted.

Sauce has been really flakey for ages.  I do have an open source account from Browserstack that they're keen for us to use but I haven't found time yet to port the test runner to work with browserstack.

**Comment by vvo** [comment]
Same issues on my side with saucelabs but wondering if browserstack would really solve them. Maybe remotely starting and controlling browsers over the internet is something that will fail no matter what :D

**Comment by triblondon** [comment]
OK, we're good here.

**Comment by vvo** [comment]
Are you planning to release 2.1 soon? Thanks

**Pull request merged**
