### PR TITLE
Symbol polyfill: Resolve cross-domain issue on IE11

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by rowanmanning** [comment]
Code looks good, but I'm not sure what the bug was. Fancy explaining when you're in?

**Comment by triblondon** [comment]
Agree, an explanation of the bug would be useful.

**Comment by JakeChampion** [comment]
This bug appears on pages which make use of iframes, an example would be `ft.com` which has ~29 iframes on it.

It appears that somehow IE11 uses the patched Object inside the iframe and can no longer access the code which originated from a different domain.

**Comment by triblondon** [comment]
> IE11 uses the patched Object inside the iframe

What.

I can't comment on this extensively, but it looks OK as a defence against that behaviour.

**Comment by JakeChampion** [comment]
I had a thought - This should probably be a part of the `Object.getOwnPropertyNames` polyfill and configuring that polyfill to target IE11. What do you think?

**Pull request merged**
