### PR TITLE
Move strict directive to top

### PR DESCRIPTION
**Pull request by DavidBruant**
It's useless if not on top.

### CODE REVIEW

**Comment by JakeChampion** [comment]
LGTM -- Currently running the tests on my machine whilst I look into the CI issues.

Thanks for the pull request!

**Comment by DavidBruant** [comment]
Sorry, it was a bold PR. I edited without testing.

**Comment by JakeChampion** [comment]
That's perfectly fine with me. You have prompted me to look into the CI issues :-)

Thanks again for ensuring we have strict usage throughout our codebase.

**Comment by triblondon** [comment]
This has been addressed in the es6 update branch.  Needed doing, so thanks for suggesting it, but we will probably just wait on #643

**Pull request closed without merging**
