### PR TITLE
fix(UA): add alias for modern yandex

### PR DESCRIPTION
**Pull request by dpolyakov**
add new aliases for modern versions of Yandex browser

### CODE REVIEW

**Comment by kaskar2008** [comment]
I've got similar PR #1768 with a little tweak for a fallback. We can merge our forks. Somehow. I guess?

**Comment by dpolyakov** [comment]
@kaskar2008 copy diff of versions mapping to your PR. I will close my PR

**Comment by dpolyakov** [comment]
closed in favor #1768

**Comment by kaskar2008** [comment]
@dpolyakov Done 👍

**Pull request closed without merging**
