### PR TITLE
Support media queries without closing parentheses

### PR DESCRIPTION
**Pull request by srolel**
Firefox, Chrome, and Edge all support this case, it might be in the spec as well but I haven't checked. Other polyfills support it as well.

### CODE REVIEW

**Comment by JakeChampion** [comment]
Hi @Mosho1, would it be possible for you to add a test for this new feature? Thanks for the PR :-)

**Comment by srolel** [comment]
Looks like this is a bit more involved, I'll review and make the additional changes later today, and add tests.

**Comment by srolel** [comment]
I've changed the implementation of the fix and added tests.

**Comment by JakeChampion** [comment]
Running the test suite :-)

**Comment by srolel** [comment]
Now that I think about it, why not use the widespread polyfill at https://github.com/paulirish/matchMedia.js?

**Comment by JakeChampion** [comment]
@Mosho1 We do offer the ability to use polyfills from npm, here is an example of how it is done -- https://github.com/Financial-Times/polyfill-service/pull/805/files

We also have documentation on authoring polyfills -- https://polyfill.io/v2/docs/contributing/authoring-polyfills

**Comment by triblondon** [comment]
I'm going to close this one - it's rather old, and a quick look at the spec does not turn up any suggestion that this parsing behaviour is part of the standard.

**Pull request closed without merging**
