### PR TITLE
Updated Symbol polyfill ios_saf to < 9

### PR DESCRIPTION
**Pull request by spencercarnage**
Per Kangax's compat table, [Symbol is supported for iOS 9 Mobile Safari](http://kangax.github.io/compat-table/es6/#test-Symbol). However, its listed as [`< 10>` in the `config.json`](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Symbol/config.json#L11). Looks like a typo because both [`Symbol.iterator`](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Symbol/iterator/config.json#L11) and [`Symbol.unscopables`](
https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Symbol/unscopables/config.json#L11) are `< 9`. 

Trying to load `?features=Symbol,Symbol.iterator` causes `Symbol.iterator` to not work for iOS 9 Mobile Safari because the polyfill for `Symbol.iterator` is not loaded and the native `Symbol` is replaced with a polyfill that is missing `iterator`. Since `Symbol` is available natively for iOS 9, this updates the config to reflect that.

I see that this [PR](https://github.com/Financial-Times/polyfill-service/pull/1115) bumped `Symbol` to `< 10`. If its preferable to leave it as-is, I can update it so that `Symbol.iterator` is `< 10` as well.

### CODE REVIEW

**Review by JakeChampion — APPROVED** [review]

**Comment by JakeChampion** [comment]
@spencercarnage Would you be able to sign our CLA?

**Comment by spencercarnage** [comment]
@JakeChampion signed.

**Comment by JakeChampion** [comment]
@spencercarnage It looks like the signing of the CLA didn't get recorded. Could you sign again using [this link](https://cla-assistant.io/Financial-Times/polyfill-service?pullRequest=1186) please?

**Comment by spencercarnage** [comment]
@JakeChampion Visiting that link, I get the message, `You have signed the CLA for Financial-Times/polyfill-service`. It shows the "sign" button briefly along with the `Please sign...` copy and then updates to show that I've signed it. Looking at the `license/cla` check for this issue, it says that `Contributor License Agreenment is not signed yet` so it looks like its not being recorded...?

**Comment by spencercarnage** [comment]
Would love to get this merged in as its biting me in the butt again on another project. I've done everything I can do sign that CLA but I can't get that badge to show that I've signed it.

screen shot 2017-09-02 at 5 35 46 pm

**Review by JakeChampion — APPROVED** [review]

**Pull request merged**
