### PR TITLE
Show aliases as part of the url builder

### PR DESCRIPTION
**Pull request by JakeChampion**
This is a first pass at showing the aliases on the url builder page, it could do with more ui/ux thought going into it.
image

### CODE REVIEW

**Comment by azizhk** [comment]
Does `alias` over here also mean dependencies?
Like will `requestAnimationFrame` have `Date.now`?

**Comment by JakeChampion** [comment]
@azizhk `alias` does not include dependencies for polyfills, `alias` is this json file --> https://unpkg.com/polyfill-library@3.31.1/polyfills/__dist/aliases.json

Did you want it to show dependencies of polyfills as well?

**Comment by azizhk** [comment]
> Did you want it to show dependencies of polyfills as well?

Well not my end use case per se.
My use case is that if I check `default` then `Array.prototype.filter` should automatically get checked. Like checked by default, which cannot be unchecked. Which on hover can say "Included as you have selected `default` bundle.

I know maybe too much trouble to implement 😅 . Can ignore.

**Comment by JakeChampion** [comment]
@azizhk That is a good feature request, could you open a new issue for it please? :-)

**Pull request merged**
