### PR TITLE
Improve DOMTokenList interface by supporting multiple arguments

### PR DESCRIPTION
**Pull request by JakeChampion**
Fixes #1006

### CODE REVIEW

**Comment by triblondon** [comment]
Test failures:
```
 - ie/11:
    -> Element.prototype.classList Should be configurable
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Element.prototype.classList
       Unable to get property 'configurable' of undefined or null reference
 - ie/10:
    -> Element.prototype.classList Should be configurable
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Element.prototype.classList
       Unable to get property 'configurable' of undefined or null reference
```

**Comment by JakeChampion** [comment]
Thanks @triblondon I completely forgot about those tests, will look into them 👍

**Review by rowanmanning — APPROVED** [review]

**Comment by robdodson** [comment]
Nice work @JakeChampion :)

Does this mean classList should eventually show up as supported in IE10-11 on polyfill.io or is there still more work to be done?

**Comment by JakeChampion** [comment]
@robdodson It will show up as supported when version 3.24 is released. Version 3.23 goes live on Friday, I am looking to make version 3.24 go to https://qa.polyfill.io on the same day.

**Comment by JakeChampion** [comment]
@robdodson Just an update, this is now on https://qa.polyfill.io alongside some other changes -- https://github.com/Financial-Times/polyfill-service/releases/tag/v3.24.0-0

**Comment by robdodson** [comment]
Wonderful! Thanks for working on this @JakeChampion :)

**Pull request merged**
