### PR TITLE
Add "android" browser to Intl locales

### PR DESCRIPTION
**Pull request by Turbo87**
This should hopefully fix the issue reported in https://github.com/Financial-Times/polyfill-service/pull/613#issuecomment-231381636

It seems that the same thing was done in https://github.com/Financial-Times/polyfill-service/pull/698 but that PR also contains other changes which seem to take longer to land.

### CODE REVIEW

**Comment by triblondon** [comment]
Thanks!

**Comment by Turbo87** [comment]
@triblondon any idea when this change will go live?

**Comment by triblondon** [comment]
It'll be a while. We're about to release 3.8 to live.  Expect 3.9 in a few weeks.

**Comment by Turbo87** [comment]
hmm, no chance for a quick bugfix release? I guess the only way around it for now is using `flags=always`

**Pull request merged**
