### PR TITLE
No versions of IE support toBlob

### PR DESCRIPTION
**Pull request by turadg**
IE11 doesn't and that's the last IE version ever.

---
This change is [Reviewable](https://reviewable.io/reviews/financial-times/polyfill-service/1258)

### CODE REVIEW

**Comment by turadg** [comment]
@JakeChampion is there anything this needs before it can be reviewed?

**Comment by JakeChampion** [comment]
IE11 supports the basic usage but not the quality parameter. The polyfill supports the quality parameter, serving this to IE11 makes sense.

Thanks for spotting this @turadg!

EDIT: IE11 has it prefixed with `ms`.

**Review by JakeChampion — APPROVED** [review]

**Comment by JakeChampion** [comment]
@turadg Can you edit the IE version range to be 10 - 11. We bundle Microsoft Edge into our IE browser detection, with the IE version range set to `*`, it will serve the polyfill to Microsoft Edge as well. We also haven't got this polyfill working in IE 7,8 or 9 which is why it only listed 10 in the version range.

**Review by JakeChampion — CHANGES_REQUESTED** [review]
Need to change the range to 10-11 to avoid targeting MS Edge or IE versions which the polyfill doesn't yet work on

**Comment by turadg** [comment]
Cool. Like that?

**Review by JakeChampion — APPROVED** [review]

**Comment by JakeChampion** [comment]
Yes, thanks @turadg!

**Comment by amarinov** [comment]
@JakeChampion @turadg I don't think Edge supports it:

image

And the polyfill **does work** for Edge:

image

**Comment by JakeChampion** [comment]
@amarinov Thanks for the comment and showing that the polyfill would infact make the tests pass. It looks like we have an issue open for Edge already -- https://github.com/Financial-Times/polyfill-service/issues/1437

**Comment by amarinov** [comment]
And btw it is supported in Safari 11.1 and tests are passed:

image

**Comment by amarinov** [comment]
Made a PR about it: #1704

**Pull request merged**
