### PR TITLE
Separate Element mutations methods

### PR DESCRIPTION
**Pull request by jonathantneal**
Resolves #288 and #286
Requires resolution to #280

### CODE REVIEW

**Comment by jonathantneal** [comment]
`Fatal error: Cannot read property 'browserName' of undefined`

Is that due to my commit, or due to Travis?

**Comment by triblondon** [comment]
It's sauce being unreliable.  Just restart the build.  Usually works 2nd or
3rd time.

**Comment by jonathantneal** [comment]
I’m on my fifth or sixth attempt of the day. Even after I removed an unused file in #287, that one has ceased passing as well. Could something else be wrong? It’s always the same error.

**Comment by triblondon** [comment]
I removed the unreliable browser (iOS 7.1) from the browsers tested in CI, and also removed the deploy tool haikro from the package manifest, which was for some reason uninstallable on Travis.  The PR should now be testable.

**Comment by jonathantneal** [comment]
Awesome blossom!

**Pull request merged**
