### PR TITLE
Add: Browser support links to contributing docs

### PR DESCRIPTION
**Pull request by andygout**
cc @triblondon @JakeChampion 

Seems like the best place to put these links; let me know if there's somewhere preferential.

### CODE REVIEW

**Comment by triblondon** [comment]
I think this needs a bit more context. If it stays in the features page, we're saying "for more information about native browser support for the features above, consult one of these resources". But I wonder how common that use case is relative to a contributor wanting to check browser support when writing or updating a config file. If you wanted to improve that area then it would be the authoring polyfills doc (though I think we do cover that quite well in the refactored docs). What are you mainly trying to achieve here?

**Comment by andygout** [comment]
I see you point and think I'm making this suggestion as a first-time polyfill-service user and that, as you suggest, it may well not be a common enough case for contributors wanting/needing to check browser support at time of contributing to warrant them, so probably best to leave them out.

**Comment by triblondon** [comment]
Didn't mean to put you off this change, Andy, sorry. It's probably a good idea, I'm just looking to understand the perspective better, since I'm obviously a bit deeper into it and can't see the wood for the trees.  If you're still keen on it do persevere and we'll find a good place for it.

**Comment by JakeChampion** [comment]
This came about through discussing how to find out which browsers support a feature prior to running tests on all the browsers. I think it would make sense in a section to do with creating or updating polyfills.

**Comment by andygout** [comment]
I'll familiarise myself with the repo a bit more to come up with some suggestions of where they could be located.

**Pull request closed without merging**
