### PR TITLE
Add missing XMLHttpRequest state code

### PR DESCRIPTION
**Pull request by ctjhoa**
According to:
- https://xhr.spec.whatwg.org/#interface-xmlhttprequest
- https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/onreadystatechange#Values

XMLHttpRequest should have constant for all possible states.
I've add some tests but I'm not sure that's relevant.

### CODE REVIEW

**Comment by JakeChampion** [comment]
@ctjhoa This looks to be failing on IE7 and IE8:

```
Failures:
 - ie/8:
    -> XMLHttpRequest
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=XMLHttpRequest
 - ie/7:
    -> XMLHttpRequest
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=XMLHttpRequest
```

**Comment by ctjhoa** [comment]
@JakeChampion Code looks good to me. Do you have any clue?   (I'm not an IE expert)

**Comment by JakeChampion** [comment]
I do not, sorry. I would recommend downloading IE7/8 or using a remote testing system such as BrosterStack or SauceLabs in order to aid investigatin the issue.

**Comment by ctjhoa** [comment]
@JakeChampion I have fixed the code it should be ok now

**Comment by ctjhoa** [comment]
@JakeChampion No feedback, is that ok?

**Comment by JakeChampion** [comment]
@ctjhoa Running the tests on CI now

**Review by JakeChampion — APPROVED** [review]

**Pull request merged**
