### PR TITLE
classList `add` should accept multiple arguments

### PR DESCRIPTION
**Pull request by ironsidevsquincy**

### CODE REVIEW

**Comment by JakeChampion** [comment]
@ironsidevsquincy Is this wanted by FT?

**Comment by ironsidevsquincy** [comment]
More just to bring it in-line with the spec

**Comment by sndrs** [comment]
this would be great if possible; we had to work round it here https://github.com/guardian/frontend/pull/16673. can we do anything to help it along?

**Comment by JakeChampion** [comment]
@sndrs We would be happy to accept a PR which would make these tests pass.

**Comment by JakeChampion** [comment]
Linking to the issue: https://github.com/Financial-Times/polyfill-service/issues/1167

**Comment by JakeChampion** [comment]
@ironsidevsquincy Would you be able to sign the CLA for this project? -- https://github.com/Financial-Times/polyfill-service/pull/1006#issuecomment-264141833

**Comment by JakeChampion** [comment]
This is being worked on in a newer PR -- https://github.com/Financial-Times/polyfill-service/pull/1347

**Pull request closed without merging**
