### PR TITLE
Support Firefox for Android

### PR DESCRIPTION
**Pull request by samgiles**
Supersedes #480

### CODE REVIEW

**Comment by samgiles** [comment]
Annoyingly Saucelabs don't support anything but the default browser on Android (whether that be Chrome or the Android stock browser)....

**Comment by samgiles** [comment]
If this could go into 2.0 it would be cool :)

**Comment by triblondon** [comment]
OK. Looks like you've changed whitespace from tabs to spaces.

**Comment by samgiles** [comment]
Easy to change except, it's because the changeset was waaaaaaaaaay larger when I made the white space consistent :P, some files are spaces, some are tabs.  I'd prefer to make the whitespace consistent as part of a separate commit, I can do that with automation.

**Comment by triblondon** [comment]
polyfills/Array/from/config.json is an example that's gone from tabs to spaces. I take your point, but since the standard is tabs, this PR should at least not introduce corrections that go the wrong way :-)

**Comment by samgiles** [comment]
Updated spaces -> tabs across all of the config files.

**Comment by alicoding** [comment]
:+1:

Just happy to see this PR :P

**Comment by triblondon** [comment]
Ok, looks fine. I'm going to wait and deploy 2.0.0 first as we're nearing the end of the RC period, so after that I'll merge this asn release it as part of 2.1.

**Comment by triblondon** [comment]
2.0.0 released.  Merging this for 2.1

**Comment by triblondon** [comment]
Cross ref: #477

**Comment by triblondon** [comment]
This is now on qa.polyfill.io.  All good?

**Pull request merged**
