### PR TITLE
Rewrite Object.assign to be spec compliant and use es abstract methods

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by 2ECC71** [comment]
Is there a timeframe for when this will be merged and deployed?

**Comment by JakeChampion** [comment]
@loxtank It is being review now and we will make a release this week

**Review by notlee — APPROVED** [review]

**Comment by 2ECC71** [comment]
@JakeChampion ok. Is there any way to use the old version in the meantime?

**Comment by JakeChampion** [comment]
@loxtank You would need to run your own version of the [server](https://www.npmjs.com/package/polyfill-service). Having versioned polyfills is on our roadmap.

**Comment by jimthedev** [comment]
I see it was merged but was it released out on the v2 endpoint?

**Comment by JakeChampion** [comment]
Not as of yet, it is marked to go out in release 3.26. We announce releases on the releases tab on GitHub (https://github.com/Financial-Times/polyfill-service/releases) and on our twitter page (https://twitter.com/polyfillio).

**Pull request merged**
