### PR TITLE
Enable `Map`, `Set`, `Array.includes` and `String.includes` polyfils for all versions of Opera Mini.

### LINKED ISSUE #897: Opera Mini - Map and Array.from polyfills missing.
Hey! Default bundle for Opera Mini doesn't seem to include `Map` and `Array.from` polyfills. My test case: http://jsbin.com/gosifujexo . When everything is OK, the page should be empty. When `Array.from` or `Map` are not available errors will be shown - like so (Opera Mini emulator):

jsbin

We load polyfill.io from CDN without any params (`<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>`) and we observed issues on wide range of Opera Mini browsers:

errors

### LINKED ISSUE #927: Opera Mini: includes
Hi!
Similar to https://github.com/Financial-Times/polyfill-service/issues/897 I noticed that the default set passed through for Opera Mini appears to be lacking support for `includes` (this is for`String`, but I am not sure of the support for `Array`). Here's a few screens from BugSnag:

screen shot 2016-10-11 at 9 39 32 am

screen shot 2016-10-11 at 9 39 40 am

### PR DESCRIPTION
**Pull request by kdzwinel**
Fixes #927
Fixes #897

### CODE REVIEW

**Comment by JakeChampion** [comment]
Hi, thanks for the contribution, have you seen our documentation for updating the targeting of a polyfill? https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

If you could show some evidence that these polyfills perform correctly in the browsers targeting by your changes that would be really helpful :-) Ideally, by including a screenshot of the relevant browsers running our test suite for these polyfills/features.

**Comment by kdzwinel** [comment]
Here are the screenshots from Opera Mini Emulator (detected as `op_mini/8` by polyfillio):

## current situation
http://jsbin.com/qorayogisi/3
https://cdn.polyfill.io/v2/polyfill.js

screen shot 2017-01-18 at 16 43 10


## with polyfills force enabled
http://jsbin.com/qorayogisi/16
https://cdn.polyfill.io/v2/polyfill.js?features=default|always|gated,Array.prototype.includes|always|gated

screen shot 2017-01-18 at 17 09 50

Official polyfill.io test doesn't seem to be working on opera mini:

screen shot 2017-01-18 at 17 14 33

**Comment by JakeChampion** [comment]
We have documentation for using the test suite -- https://polyfill.io/v2/docs/contributing/testing#running-tests-locally

`Map`: https://polyfill.io/test/tests?feature=Map&mode=all

`Set`: https://polyfill.io/test/tests?feature=Set&mode=all

`Array.prototype.includes`: https://polyfill.io/test/tests?feature=Array.prototype.includes&mode=all

`String.prototype.includes`: https://polyfill.io/test/tests?feature=String.prototype.includes&mode=all

**Comment by triblondon** [comment]
@kdzwinel Could you run the standalone test pages on your test browser and report back to enable us to merge this?

**Comment by JakeChampion** [comment]
@kdzwinel Are you able to help us finish this PR. If you don't have the time anymore to work on this, that's okay, I will try and hunt down an opera mini device to test this on.

**Comment by JakeChampion** [comment]
@kdzwinel I tested these on Opera mobile 7.5 :-)
screen shot 2017-09-01 at 10 10 32
screen shot 2017-09-01 at 10 10 10
screen shot 2017-09-01 at 10 09 23
screen shot 2017-09-01 at 10 09 02

**Comment by JakeChampion** [comment]
Here they are on the live site for comparison
screen shot 2017-09-01 at 10 17 32
screen shot 2017-09-01 at 10 16 58
screen shot 2017-09-01 at 10 15 20
screen shot 2017-09-01 at 10 15 02

**Comment by JakeChampion** [comment]
<details>
<summary>Browser version op_mini/8:</summary>
browser version</details>


Results on live site:
<details>
<summary>Map - tests don't run</summary>
live-map
</details>
<details>
<summary>Set - tests fail</summary>
live-set
</details>
<details>
<summary>Array - tests don't run</summary>
live-array
</details>
<details>
<summary>String - basic existence tests pass (we don't have other tests)</summary>
live-string
</details>

Results from PR:
<details>
<summary>Map - tests pass</summary>
pr-map
</details>
<details>
<summary>Set - tests pass</summary>
pr-set
</details>
<details>
<summary>Array - tests pass</summary>
pr-array</details>
<details>
<summary>String - basic existence tests pass</summary>
pr-string</details>

**Review by JakeChampion — APPROVED** [review]

**Pull request merged**
