### PR TITLE
Remove a not own property constraint for iterators in Array.from

### LINKED ISSUE #816: Array.from function doesn't work with iterators such as Map/Set methods entries/keys/values
`Array.from`, `Map`, and `Set` are polyfills.

``` js
Array.from(new Map().set(0, 0).entries());
Array.from(new Set().add(0).entries());
```

expected:

```
[[0, 0]]
[0]
```

actual:

```
[]
[]
```

### PR DESCRIPTION
**Pull request by falsandtru**
Fixes #816.

### CODE REVIEW

**Comment by falsandtru** [comment]
@triblondon @JakeChampion Can you take a look? Note, I don't have api keys of saucelabs. How can I resolve the following error?

```
Warning: SAUCE_USER_NAME and SAUCE_API_KEY must be set in the environment Use --force to continue.
```

**Comment by JakeChampion** [comment]
I've resolved this issue by bring your forked repository's branch into our origin repository. CI now passes :-)

**Comment by falsandtru** [comment]
Thanks! Could you merge this?

**Comment by JakeChampion** [comment]
Would you be able to add a test to cover this change?

**Comment by falsandtru** [comment]
This change is already covered in the following test.

https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Array/from/tests.js#L46

But old code passed this test even though it should be failed. Then I don't know how can I test this change using polyfills. Have you any ideas?

**Comment by JakeChampion** [comment]
Ah yes, that is because we only install the polyfills which the requested polyfill needs to function. `Array.from` does not need `Set` or `Map` polyfills to function so they are not downloaded. This in turn means those tests you linked to would not run as `Set` and `Map` would not be present.

If we create a custom iterable object and use that in the tests then we can test this code path in older browsers which don't have `Set` or `Map`.

**Comment by falsandtru** [comment]
Okay, I'll try it.

**Comment by JakeChampion** [comment]
Great work @falsandtru !

**Comment by falsandtru** [comment]
Thanks @JakeChampion !

**Comment by JakeChampion** [comment]
@falsandtru I forgot to ask if you are okay with our contribution terms, apologies for that. Our terms can be [found here](https://cdn.polyfill.io/v2/docs/contributing#contribution-terms).

**Comment by falsandtru** [comment]
I agree, this is a wholly my own work, and you can use this under your license.

**Comment by falsandtru** [comment]
@JakeChampion Could you delete the `array.from` branch for the next pr?

**Comment by falsandtru** [comment]
Sorry, I found the workaround.

**Pull request merged**
