### PR TITLE
Add hsts header

### PR DESCRIPTION
**Pull request by JakeChampion**
Resolves -- https://github.com/Financial-Times/polyfill-service/issues/646

### CODE REVIEW

**Comment by triblondon** [comment]
Do we really need an additional dependency to write a single line, static HTTP header?

**Comment by JakeChampion** [comment]
@triblondon I removed the module and added the header. Ready for review.

**Comment by triblondon** [comment]
Ok, this looks fine. No need for the moment upgrade but no harm I guess. Not sure it's obvious to me why you chose 18 weeks, so if there was a reason, a comment in the code would be useful.

**Comment by JakeChampion** [comment]
@triblondon Switched to one_year

**Pull request merged**
