### PR TITLE
Added bb to array includes config

### PR DESCRIPTION
**Pull request by wheresrhys**
@JakeChampion

### CODE REVIEW

**Comment by JakeChampion** [comment]
@wheresrhys Could you follow the steps outlined on our contribution page please? https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by wheresrhys** [comment]
> Check reliable sources of browser support information, e.g. MDN, caniuse and Kangax. Tell us what these sources say about the browser/polyfill combo that you want to add or remove, and link to the relevant pages from your PR.

Sources are hard to come by for BB devices e.g. not listed here https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

> Explain how you have tested support (or lack of) in the browser concerned. Ideally, include a screenshot of the relevant browser running our test suite for that feature.

ft.com uses `Array.prototype.includes|always|gated` at the moment, and the feature appears to be polyfilled correctly on BB10 devices

**Comment by wheresrhys** [comment]
I'll verify properly on a bb7 & bb10 soon

**Comment by wheresrhys** [comment]
Verified on bb10
image

**Comment by triblondon** [comment]
Nice "screenshot"

**Review by JakeChampion — APPROVED** [review]

**Pull request merged**
