### PR TITLE
Fix Set iteration bug #949

### LINKED ISSUE #949: Bug with Set polyfill
When the last entry in the set becomes deleted, the iterator will never be 'done'.

Example:

```
let myset, entries, current;

myset = new Set();
myset.add('lol');
myset.add('wut');

entries = myset.entries();
current = entries.next();
console.assert(current.done === false, "A");
console.assert(current.value[0] === 'lol', "B");
current = entries.next();
console.assert(current.done === false, "C");
console.assert(current.value[0] === 'wut', "D");
current = entries.next();
console.assert(current.done === true, "E");
console.assert(typeof current.value === 'undefined', "F");

myset.delete('wut');

entries = myset.entries();
current = entries.next();
console.assert(current.done === false, "W");
console.assert(current.value[0] === 'lol', "X");
current = entries.next();
console.assert(current.done === true, "Y");
console.assert(typeof current.value === 'undefined', "Z");
```

The last two assertions will fail. This leads to bugs when trying to use `forEach`.

### PR DESCRIPTION
**Pull request by tuespetre**

### CODE REVIEW

**Comment by JakeChampion** [comment]
Thanks for the PR @tuespetre, would you be able to add a test for this? I believe the code you posted in https://github.com/Financial-Times/polyfill-service/issues/949#issue-184732549 would suffice.

**Comment by tuespetre** [comment]
Sure. I will try and find some time later today.

**Review by JakeChampion — APPROVED** [review]

**Comment by JakeChampion** [comment]
@tuespetre Looks good, would you be able to read through our contribution terms, if you agree to those then I can merge this in :-) -- https://polyfill.io/v2/docs/contributing#contribution-terms

**Comment by tuespetre** [comment]
I do agree to those terms 👍

**Comment by JakeChampion** [comment]
Thanks for the contribution @tuespetre. Did you know we offer one month's free premium access to all FT content (normally $50) to anyone who has a pull request merged in this repository? If you want to claim it, there's [one Google form](https://docs.google.com/a/ft.com/forms/d/1aykPiYBwqKpKY6nvGVi43wOU_5epr3XLgE00Vi52SMQ/viewform) to fill out :-)

**Comment by tuespetre** [comment]
Thanks! Claim made ✔️

**Pull request merged**
