### PR TITLE
Rhys/dom iterators

### PR DESCRIPTION
**Pull request by wheresrhys**
@JakeChampion

### CODE REVIEW

**Comment by JakeChampion** [comment]
I think you need to execute the function expression on line 5 of
`polyfills/DOMTokenList/prototype/@@iterator/detect.js` &
`polyfills/NodeList/prototype/@@iterator/detect.js`, I believe they are
currently returning either a boolean or a function when they need to only
return a boolean.

**Comment by wheresrhys** [comment]
yep - I have the annoying habit of submitting PRs as part of my personal QA workflow. It _should_ now pass all tests

**Comment by JakeChampion** [comment]
Looks good to me. I'm away from a machine so cannot merge it. Feel free to
merge in to master.

**Comment by wheresrhys** [comment]
I'm gonna add samsung browser first

**Comment by wheresrhys** [comment]
@AdaRoseEdwards Jake tells me you're the samsung browser config guru. Would you mind fleshing out these configs to include samsung browser (It'd be good to also revisit Array.prototype.@@iterator, values, keys and entries as they don't target samsung, and are also a blocker for us turning off core-js Symbol & iterator polyfills in favour of polyfill.io)

**Comment by JakeChampion** [comment]
Merging this in, @AdaRoseEdwards can add the Samsung configurations in a later PR :-)

**Pull request merged**
